### =========================================================== ###
### localhost:8080
###
GET http://localhost:8080/ HTTP/1.1

###
POST http://localhost:8080/ HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "email@doe.com",
    "favoriteColor": "monotonic shades",
    "birthday": "NT/4U/1999"
}

###
GET http://localhost:8080/65e151deec9a15a38013027b HTTP/1.1

###
PUT http://localhost:8080/65e151deec9a15a38013027b HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johnnyboi@doe.com",
    "favoriteColor": "dark colors",
    "birthday": "NT/4U/1999"
}

###
POST http://localhost:8080/ HTTP/1.1
content-type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "janet@doe.com",
    "favoriteColor": "pretty colors",
    "birthday": "NT/4U/2000"
}

###
GET http://localhost:8080/ HTTP/1.1

###
GET http://localhost:8080/65e151f4ec9a15a38013027c HTTP/1.1

###
DELETE http://localhost:8080/65e151f4ec9a15a38013027c HTTP/1.1

###
DELETE http://localhost:8080/65e151deec9a15a38013027b HTTP/1.1

### =========================================================== ###
### Render
###
GET https://contacts-ia6n.onrender.com/ HTTP/1.1

###
POST https://contacts-ia6n.onrender.com/ HTTP/1.1
content-type: application/json

{
    "firstName": "Maggie",
    "lastName": "Bechtel",
    "email": "magstergirlygirl@gmail.com",
    "favoriteColor": "red",
    "birthday": "10/05/1998"
}

###
GET https://contacts-ia6n.onrender.com/65e14f5cec9a15a38013027a HTTP/1.1

###
PUT https://contacts-ia6n.onrender.com/65e14f5cec9a15a38013027a HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "email@doe.com",
    "favoriteColor": "dark colors",
    "birthday": "NT/4U/1999"
}

###
POST https://contacts-ia6n.onrender.com/ HTTP/1.1
content-type: application/json

{
    "firstName": "Richelle",
    "lastName": "Fowler",
    "email": "richellefowler5@gmail.com",
    "favoriteColor": "pretty colors",
    "birthday": "NT/4U/2000"
}

###
GET https://contacts-ia6n.onrender.com/ HTTP/1.1

###
GET https://contacts-ia6n.onrender.com/65e14f57ec9a15a380130279 HTTP/1.1

###
DELETE https://contacts-ia6n.onrender.com/65e14f57ec9a15a380130279 HTTP/1.1

###
DELETE https://contacts-ia6n.onrender.com/65e14f5cec9a15a38013027a HTTP/1.1

###
GET https://contacts-ia6n.onrender.com/ HTTP/1.1